package team;

public class clas {
public static void main(String[] args) {
System.out.println(
"┌─────────┐\r\n"
+ "│ ♠1      │\r\n"
+ "│         │\r\n"
+ "│         │\r\n"
+ "│    ♠    │\r\n"
+ "│         │\r\n"
+ "│         │\r\n"
+ "│      ♠1 │\r\n"
+ "└─────────┘ "
		);



System.out.println(
		"                                                       ::7v7X5SUqbbPd5777..                                             \r\n"
		+ "                                                  .:ir:::...    .i:iir7sJUU217i.                                        \r\n"
		+ "                                              7jS5UYvr:.......:irrrr77vvJs1u5KPEgE1:                                    \r\n"
		+ "                                           :jXJvrriiiiiriiirirrrirrrrv7YLJYuJ1u1uIXZZKr.                                \r\n"
		+ "                                        .7S2vrririi:i:iiiiiiririrrrrr7vvJJ1jU1UjUjuJUIdZPr                              \r\n"
		+ "                                      i15Jrrrriiii:i:i:iiiiiiiiiirrrr77vrrr777LuJUu1JJsj1PEJ                            \r\n"
		+ "                                    s5U7rrrrririiii:i:iiiiiiriiirirr7ri:::iiiiri7vYJ1JjYJLsIPi                          \r\n"
		+ "                                  7XY7r7r7rriiiiiriiiiiiiiiiiiiriii7i::::iiiirrrrrrr71JJLYvvLX2:                        \r\n"
		+ "                                iS277ri:....... ..:iriiiiiiiiiiiiirri.::::iirirr7rrrrrYjJvL7v7Yqu                       \r\n"
		+ "                              .5Xv::.............. .:riiiiiiiiiiiriri::::i:iiiirrrrrrrr7LjLL7v775S                      \r\n"
		+ "                             sP7:.................. .iiiiiiiiiririrrr.::::::iiiirirrrr7ir7vvv77r72q                     \r\n"
		+ "                           rXY:.................... .riiiiiiiriiirirrr:::::iiiiiirirrrrrir7Lvv77rrdr                    \r\n"
		+ "                         :I2i...:...................iiiiiiiiiiririrrr77:::::::iiiirirrriirLvv777777b                    \r\n"
		+ "                     .ij55v7.............. . . ..:irriiiiiiriririrrrrr7v7rii:::i:iiiiiiirsYLvv7777iJv                   \r\n"
		+ "                  .7SS2v7r7ri:.......   .....:i:rrririiiiiririrrrirrrr7777Lvvr77ririir7vYYYvY7L77rr:q.                  \r\n"
		+ "              .iJKX17rrriiiiir::::.:.::iiiiiiririiiiiiiiiiiiiririrrrrrr7777vvvvYvYvYvYvYvYvLLLvv7vrii5.                 \r\n"
		+ "          irLvvri.:iriiii:::i:iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirirrrrrr7r7r7777vvLvYvLvLvvvLLYLsLLvL77rq:                \r\n"
		+ "      .777i:.......iii:i:::::::::::::i:i:iiiiiiiiiiiiiiiiriiiririrrrrrr7rrr7777v7L7vvv7LvLvLvYLJvYvLvv7Pr               \r\n"
		+ "     r7:...........ii:i:i:i:::::::::::::i:iiiii:iiiiiiiiiiiiriririrrrrrr7r7r7777v7v7v7v7v7LLsYJYJYsvvvv7Xv              \r\n"
		+ "   iv:...:........iiiiiiiiii:i:::::::::::::i:i:iiiiiiiiiiiiiiiiiiiirirrrr7r7r77777777vvvvvvsYuJujuJJYLvv7uXr            \r\n"
		+ "  Y7..:.::::::::::7rririiiiiiii:i:::::::::i:i:i:iiiiiiiiiiiiiiiiiirirrrrrr7r7r7r77v7v7vvYLsvY777v7vvsLJvL7vU5.          \r\n"
		+ " :J..::iirr7r7r7r71usJvLvv77rririi:i:i:::::::i:iiiirirrrrrriiiiiiririiirrrrrrrrrr7777vvs7iiiiiirirrrrrrLLYvvvXs         \r\n"
		+ " 27ii:ir77777r7vY1I1Uj1JusjYsvv77rriiii:i:i:iiiii:::::::::irrrriiiiiiiriririrrrrrr7rv77ii:iirirrrrrrrrri7vYvv7uX7       \r\n"
		+ "vJrJJJYL7v7YYJsU1UjusuJususuJujjssvv77iriiiiii.... . ........iiriiiiiiiriririrrrr7r7rLi::iiiirirrrrrrrrri7vYvLvvIq:     \r\n"
		+ "BiLjUUIUUuusJYsvYvv7v7v7LvYLJsjJuJJYsvL7v77ri..................:iiiiiiiiriiirirrrrrr77i:i:iiiirirrrrrrrrrrLLsLsvYJdI.   \r\n"
		+ "QrYujUJuLv7JuIU5UI2I2525uUsJY1sjLJssYsYJYYL7::::.:...............iiiiiiiiriiiiirirrrrvi::i:iiiirrrrrrrrri7JJYsYsLssSdu  \r\n"
		+ "BrJJuss7rr2U1j1u2IKXqqPqPqbDP72IUjsLJsJsJLJriiriiii::::.:.........:iiiiiiiiiiiiirrrrrr7:::::i:iirirr7rrirv1sJYjYJYJsubP \r\n"
		+ "2uvJYs77iKjYLJuI5KSqKqKPXPdgi.:rv12IuJYJYJs7irrrrririiii:i::::.:...iiririiiririrrrrrr7i:.::i:iiiirrrrri7L1J1jujuJuJjJjbr\r\n"
		+ ".qJsjv7rrKYYI2I121U2S5K5XXDi:iii:ir7jU211sJ7irrrrrrrrrriririi:i::::i7rrrrrrrrrrrrrrr7r7i:.::::i:iirirrLj2u1u1uUuUu1jUju5\r\n"
		+ " UXUjJv7iX25JJsJs25qXqKqKMs.irrrrrrrir7sJUI27riiirirrrrrirrririiiiiL7v7v7v7v7v777v7v7vvY77rrirrrr77sYUII12UUUU1U121U11YK\r\n"
		+ "  BYvv7i:rgusYssIIIIIISSD2::iiiirrrrrrriii77JsjYL7riiirirrrrrrriiiLYYLYLJLjsjsjsjsJsJYjJ1U2UI25ISI5I5UIUUuUuuu2u21UU2jJ2\r\n"
		+ "  .usriii:iUUsj5JJYuj2IdU::i::::irr7r7r7rrrrirr7vssuLY7ririiiiiirjsJYsLsYjJuJ1J1j1j1jUuUu2U212U21I1UuusJvYvYLJJ112U21u7U\r\n"
		+ "    iIJrri::r1EJjsJsu1PJ::rJQBR2i:rr7r7r7r7r7r7rrrrrvvYsJYJLL7Jj2sJYsvYLsYjsuJjJuJ1j1j1jUuU11uUJuYYv777v1LvvssU12U21Uvrs\r\n"
		+ "      7q1vri:vuUUI25SKv::Xr  BBBBLi77v7v777777r7r7r7rrirrr777LLuJUu2uUuUu1sjYsYjYJsjJjJusuj1JuJujsvYYJjUsYvjJ1121IUUL7iu\r\n"
		+ "        iL5XP2svvvUP2::::QBvqBQBBQ..::iirr77v7v7v77r777r7r7rrrriiii:::i7YLUjUU22IUIUIU22I2I2IUIsvuPJjYYvsYujU1IISISs7r7Y\r\n"
		+ "           .7SPP5Kj: ... EBBBBBBBJ       ....::irrr7777vr7r7r7rriv5QdKr::iiiiririrrririiiiii::::.:XYLsYJsuJu1IuuLvrrirP:\r\n"
		+ "               .I7  ...   rBBBBBi               ...::irr77v77rriP. iBBBEii7rrrrrrrrrrrriririi:i:: 15JsJYJsjuU77rr::::72 \r\n"
		+ "              .i.  .         .       .r                .:ir7r7rrBE:PBQBBXirrrrrrr7rrr7rrrririi:::..dYsYjYjsuLrii:::iv5  \r\n"
		+ "             ri.  .                  :7   .      i:       ..::i:BBBQBQBBj:rrrrrrrrrrrrrrrrrrrii::..7qYJsJsUviii:::rJs   \r\n"
		+ "           iv. . .                    .ir::i:....r           ...:EQBBBQs:rr7r7r7rrrrrrrrrrrriiii::..XusYLv7r:ii7v1v.    \r\n"
		+ "          r7  . .                           .:i:.                 :rv7::rr7r7rrrrrrrrrrrrrrrriri::: rI77v7YLsu1v:       \r\n"
		+ "         rv ..                                                       .:ir7r7rrr7rrrrrrirrrirrrii:::..q2IIjvi.           \r\n"
		+ "        .U ..                                                         .:ir7rrrrr7r7rrrrrrrriririi::..U                  \r\n"
		+ "        I. ...                                                         ..:irrrrrrrrrrririrrririi:::..S                  \r\n"
		+ "       :s ...                                                             .:irrirrrrrrrrrrririiii::..S                  \r\n"
		+ "       I....                                                               ..iirrrrrrririririiii::...S                  \r\n"
		+ "       S.....                                                               ..:iririririririiii::::..5                  \r\n"
		+ "       S....                                                                 ..:iiiiiriiiriiii::::...S                  \r\n"
		+ "       S....                                                                  ..:iiiiiiiiirii:i::::..S                  \r\n"
		+ "       q....                                                                   ..::iiiiiiiii:i:i::...S                  \r\n"
		+ "       vr ...                                                                    .::i:iiiiiii::::::.rv                  \r\n"
		+ "        S....                                                                    ..::i:iiiiiii::::..2.                  \r\n"
		+ "        rL.....                                                                   .:::i:iii:i:::::.:5                   \r\n"
		+ "         s7....                                                                    ::::::i:i::::::.S.                   \r\n"
		+ "          s7.....                                                                 ..::::::::::::..U:                    \r\n"
		+ "           r7:....                                                               ....::::::::::..1:                     \r\n"
		+ "             r7....                                                               ..:.::::::::.:2.                      \r\n"
		+ "              .v7i....                                                           ....:::::::..iI                        \r\n"
		+ "                .rvi.....                                                       ......:::::.ivr                         \r\n"
		+ "                   rvvi:.... .                                                 ......:.:..:vr.                          \r\n"
		+ "                     .:7Lr:......                                           ............ivL.                            \r\n"
		+ "                         :rL7r:......... .                               ............i7Yi.                              \r\n"
		+ "                            .:7vvri:....................... .....................:r7vi.                                 \r\n"
		+ "                                 .:r7vrr::.................................::r7v7r:.                                    \r\n"
		+ "                                      ..iiv7777rrii:i:i:i:i:i:i:i:iiirrrv777r:.                                         \r\n"
		+ "                                                  ...................                                                ");

}


}
